### ISSUE TITLE
Zenders does not work anymore

### ISSUE THREAD

**Issue by wvanderwees** [ziggotv/ziggotv.github.io#4] opened 2024-08-09 12:54 UTC
Since version 1.0.8, when you click on "Zenders" you get the message "The parameter "genre" must be either a Tuple or a List." and you cannot select a channel. You can select and play a channel via the EPG only.

**Comment by tgiesela** [comment] 2024-08-09 13:40
Should be fixed in version 1.0.10. It was caused by unexpected data in channel information ('genre' is empty for some channels).

**Closed by tgiesela** 2024-08-09 13:40 UTC

**Comment by wvanderwees** [comment] 2024-08-09 14:49
Werkt helaas nog niet

**Comment by tgiesela** [comment] 2024-08-09 14:57
Are you sure you have version 1.0.10 installed? Please check under My Add-ons/Video add-ons.
For me it works fine now. 
Do you still get the same error? If so, please provide a debug log.

**Comment by wvanderwees** [comment] 2024-08-10 10:39
Sorry voor het misverstand maar had inderdaad nog 1.0.9 draaien.

Het werkt weer perfect nu.

Wederom bedankt voor deze geweldige app!

 

Met vriendelijke groet,

Wilfred van der Wees.
